/*
###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID edatools-server1.iiitd.edu.in)
#  Generated on:      Wed Sep 16 20:02:15 2026
#  Design:            simple_mac
#  Command:           saveNetlist ../pnr_report/simple_mac_routed.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Sep 15 2026 13:46:02 IST (Sep 15 2026 08:16:02 UTC)
// Verification Directory fv/simple_mac 
module add_unsigned (
	A, 
	B, 
	Z);
   input [15:0] A;
   input [15:0] B;
   output [15:0] Z;

   // Internal wires
   wire UNCONNECTED;
   wire n_0;
   wire n_2;
   wire n_3;
   wire n_5;
   wire n_9;
   wire n_11;
   wire n_13;
   wire n_15;
   wire n_17;
   wire n_19;
   wire n_21;
   wire n_23;
   wire n_25;
   wire n_26;
   wire n_31;
   wire n_33;
   wire n_35;
   wire n_37;
   wire n_39;
   wire n_73;
   wire n_76;
   wire n_78;

   ADDFHX1 g1052 (.A(B[14]),
	.B(A[14]),
	.CI(n_37),
	.CO(n_39),
	.S(Z[14]));
   ADDFHX1 g1053 (.A(B[13]),
	.B(A[13]),
	.CI(n_35),
	.CO(n_37),
	.S(Z[13]));
   ADDFHX1 g1054 (.A(B[12]),
	.B(A[12]),
	.CI(n_33),
	.CO(n_35),
	.S(Z[12]));
   ADDFHX1 g1055 (.A(B[11]),
	.B(A[11]),
	.CI(n_31),
	.CO(n_33),
	.S(Z[11]));
   ADDFX1 g1056 (.A(B[10]),
	.B(A[10]),
	.CI(n_76),
	.CO(n_31),
	.S(Z[10]));
   XNOR3X1 g1057 (.A(B[9]),
	.B(A[9]),
	.C(n_3),
	.Y(Z[9]));
   XNOR3X1 g1060 (.A(B[8]),
	.B(A[8]),
	.C(n_5),
	.Y(Z[8]));
   XNOR3X1 g1065 (.A(B[7]),
	.B(A[7]),
	.C(n_25),
	.Y(Z[7]));
   NOR2X2 g1066 (.A(n_9),
	.B(n_25),
	.Y(n_26));
   INVX2 g1067 (.A(n_23),
	.Y(n_25));
   ADDFHX1 g1068 (.A(B[6]),
	.B(A[6]),
	.CI(n_21),
	.CO(n_23),
	.S(Z[6]));
   ADDFHX1 g1069 (.A(B[5]),
	.B(A[5]),
	.CI(n_19),
	.CO(n_21),
	.S(Z[5]));
   ADDFHX1 g1070 (.A(B[4]),
	.B(A[4]),
	.CI(n_17),
	.CO(n_19),
	.S(Z[4]));
   ADDFX1 g1071 (.A(B[3]),
	.B(A[3]),
	.CI(n_15),
	.CO(n_17),
	.S(Z[3]));
   ADDFX1 g1072 (.A(B[2]),
	.B(A[2]),
	.CI(n_13),
	.CO(n_15),
	.S(Z[2]));
   ADDFX1 g1073 (.A(B[1]),
	.B(A[1]),
	.CI(n_78),
	.CO(n_13),
	.S(Z[1]));
   NAND2X1 g1076 (.A(B[8]),
	.B(A[8]),
	.Y(n_11));
   NOR2XL g1081 (.A(B[7]),
	.B(A[7]),
	.Y(n_9));
   AOI2BB1X1 g2 (.A0N(n_9),
	.A1N(n_25),
	.B0(n_2),
	.Y(n_5));
   XOR3XL g1090 (.A(B[15]),
	.B(A[15]),
	.C(n_39),
	.Y(Z[15]));
   AND2X1 g1091 (.A(n_11),
	.B(n_0),
	.Y(n_3));
   AND2X1 g1092 (.A(B[7]),
	.B(A[7]),
	.Y(n_2));
   OAI22X4 g1094 (.A0(B[8]),
	.A1(A[8]),
	.B0(n_2),
	.B1(n_26),
	.Y(n_0));
   NAND2X4 g3 (.A(n_0),
	.B(n_11),
	.Y(n_73));
   ADDFHX1 g1096 (.A(n_73),
	.B(B[9]),
	.CI(A[9]),
	.CO(n_76),
	.S(UNCONNECTED));
   ADDHXL g1097 (.A(B[0]),
	.B(A[0]),
	.CO(n_78),
	.S(Z[0]));
endmodule

module mult_unsigned (
	A, 
	B, 
	Z);
   input [7:0] A;
   input [7:0] B;
   output [15:0] Z;

   // Internal wires
   wire FE_OCPN3_n_103;
   wire FE_OFN2_n_107;
   wire FE_OFN1_n_107;
   wire FE_OFN0_n_105;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_14;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_21;
   wire n_23;
   wire n_24;
   wire n_28;
   wire n_30;
   wire n_32;
   wire n_34;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_192;
   wire n_193;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_213;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_245;
   wire n_246;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_253;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_269;
   wire n_270;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_274;
   wire n_275;
   wire n_276;
   wire n_277;
   wire n_279;
   wire n_281;
   wire n_282;
   wire n_283;
   wire n_285;
   wire n_286;
   wire n_288;
   wire n_290;
   wire n_292;
   wire n_294;
   wire n_312;
   wire n_313;
   wire n_314;
   wire n_315;
   wire n_316;
   wire n_317;
   wire n_318;
   wire n_319;

   XNOR2X1 FE_RC_3_0 (.A(n_249),
	.B(n_18),
	.Y(n_276));
   XNOR2X1 FE_RC_2_0 (.A(n_204),
	.B(n_211),
	.Y(n_245));
   XNOR2X1 FE_RC_1_0 (.A(n_312),
	.B(n_16),
	.Y(n_265));
   XNOR2X1 FE_RC_0_0 (.A(n_124),
	.B(n_140),
	.Y(n_192));
   CLKBUFX6 FE_OCPC6_n_103 (.A(B[1]),
	.Y(FE_OCPN3_n_103));
   BUFX2 FE_OFC5_n_107 (.A(n_34),
	.Y(FE_OFN2_n_107));
   INVX2 FE_OFC4_n_107 (.A(n_34),
	.Y(FE_OFN1_n_107));
   INVX2 FE_OFC3_n_107 (.A(B[5]),
	.Y(n_34));
   INVX1 FE_OFC2_n_2 (.A(n_2),
	.Y(n_66));
   INVX4 FE_OFC1_n_105 (.A(n_28),
	.Y(FE_OFN0_n_105));
   INVX4 FE_OFC0_n_105 (.A(B[3]),
	.Y(n_28));
   ADDFHX1 g3822 (.A(n_245),
	.B(n_260),
	.CI(n_292),
	.CO(n_294),
	.S(Z[14]));
   ADDFHX2 g3823 (.A(n_266),
	.B(n_259),
	.CI(n_290),
	.CO(n_292),
	.S(Z[13]));
   ADDFHX1 g3824 (.A(n_275),
	.B(n_265),
	.CI(n_288),
	.CO(n_290),
	.S(Z[12]));
   ADDFHX1 g3825 (.A(n_273),
	.B(n_276),
	.CI(n_286),
	.CO(n_288),
	.S(Z[11]));
   ADDFHX2 g3826 (.A(n_267),
	.B(n_274),
	.CI(n_285),
	.CO(n_286),
	.S(Z[10]));
   OAI222X4 g3828 (.A0(n_271),
	.A1(n_272),
	.B0(n_272),
	.B1(n_283),
	.C0(n_262),
	.C1(n_256),
	.Y(n_285));
   XNOR3X1 g3830 (.A(n_268),
	.B(n_264),
	.C(n_23),
	.Y(Z[8]));
   OAI2BB2X4 g3832 (.A0N(n_258),
	.A1N(n_263),
	.B0(n_270),
	.B1(n_282),
	.Y(n_283));
   NOR2X2 g3836 (.A(n_269),
	.B(n_281),
	.Y(n_282));
   INVX3 g3837 (.A(n_279),
	.Y(n_281));
   ADDFHX1 g3838 (.A(n_224),
	.B(n_317),
	.CI(n_277),
	.CO(n_279),
	.S(Z[6]));
   ADDFHX2 g3839 (.A(n_225),
	.B(n_213),
	.CI(n_257),
	.CO(n_277),
	.S(Z[5]));
   OAI2BB2XL g3841 (.A0N(n_232),
	.A1N(n_251),
	.B0(n_249),
	.B1(n_261),
	.Y(n_275));
   ADDFX1 g3842 (.A(n_9),
	.B(n_10),
	.CI(n_246),
	.CO(n_273),
	.S(n_274));
   CLKAND2X3 g3843 (.A(n_262),
	.B(n_256),
	.Y(n_272));
   NAND2X2 g3846 (.A(n_268),
	.B(n_264),
	.Y(n_271));
   NOR2X1 g3848 (.A(n_319),
	.B(n_17),
	.Y(n_270));
   CLKAND2X2 g3849 (.A(n_319),
	.B(n_17),
	.Y(n_269));
   INVX1 g3851 (.A(n_258),
	.Y(n_268));
   ACHCONX2 g3853 (.A(n_242),
	.B(n_215),
	.CI(n_11),
	.CON(n_267));
   OAI2BB2XL g3854 (.A0N(n_231),
	.A1N(n_12),
	.B0(n_312),
	.B1(n_250),
	.Y(n_266));
   INVX2 g3856 (.A(n_263),
	.Y(n_264));
   ADDFX1 g3858 (.A(n_314),
	.B(n_226),
	.CI(n_241),
	.CO(n_262),
	.S(n_263));
   NOR2XL g3859 (.A(n_232),
	.B(n_251),
	.Y(n_261));
   ACHCONX2 g3860 (.A(n_151),
	.B(n_243),
	.CI(n_237),
	.CON(n_260));
   XNOR3X1 g3861 (.A(n_151),
	.B(n_227),
	.C(n_216),
	.Y(n_259));
   AOI2BB2X1 g3862 (.A0N(n_207),
	.A1N(n_222),
	.B0(n_239),
	.B1(n_235),
	.Y(n_258));
   OAI21X2 g3864 (.A0(n_255),
	.A1(n_240),
	.B0(n_238),
	.Y(n_257));
   XOR3X1 g3865 (.A(n_242),
	.B(n_215),
	.C(n_11),
	.Y(n_256));
   INVX1 g3869 (.A(n_253),
	.Y(n_255));
   ADDFHX1 g3870 (.A(n_175),
	.B(n_192),
	.CI(n_220),
	.CO(n_253),
	.S(Z[3]));
   OAI2BB2XL g3874 (.A0N(n_205),
	.A1N(n_228),
	.B0(n_205),
	.B1(n_228),
	.Y(n_251));
   NOR2XL g3875 (.A(n_231),
	.B(n_12),
	.Y(n_250));
   AOI2BB2X1 g3878 (.A0N(n_149),
	.A1N(n_179),
	.B0(n_195),
	.B1(n_233),
	.Y(n_249));
   OAI2BB2XL g3882 (.A0N(n_149),
	.A1N(n_153),
	.B0(n_200),
	.B1(n_229),
	.Y(n_246));
   INVX1 g3887 (.A(n_227),
	.Y(n_243));
   ADDFX1 g3888 (.A(n_170),
	.B(n_146),
	.CI(n_171),
	.CO(n_242),
	.S(n_241));
   NOR2X1 g3889 (.A(n_3),
	.B(n_230),
	.Y(n_240));
   NAND2X1 g3890 (.A(n_207),
	.B(n_222),
	.Y(n_239));
   NAND2X1 g3891 (.A(n_3),
	.B(n_230),
	.Y(n_238));
   INVX1 g3893 (.A(n_216),
	.Y(n_237));
   INVX1 g3895 (.A(n_234),
	.Y(n_235));
   INVX1 g3896 (.A(n_201),
	.Y(n_233));
   INVX1 g3899 (.A(n_217),
	.Y(n_232));
   INVX1 g3900 (.A(n_210),
	.Y(n_231));
   INVX1 g3902 (.A(n_316),
	.Y(n_229));
   ADDFX1 g3903 (.A(n_145),
	.B(n_144),
	.CI(n_147),
	.CO(n_226),
	.S(n_234));
   ADDFX1 g3904 (.A(n_121),
	.B(n_135),
	.CI(n_148),
	.CO(n_225),
	.S(n_230));
   AOI2BB2X1 g3905 (.A0N(n_131),
	.A1N(n_181),
	.B0(n_169),
	.B1(n_197),
	.Y(n_228));
   OAI2BB2XL g3906 (.A0N(n_55),
	.A1N(n_154),
	.B0(n_152),
	.B1(n_196),
	.Y(n_227));
   ACHCONX2 g3907 (.A(n_159),
	.B(n_166),
	.CI(n_209),
	.CON(n_224));
   XNOR3XL g3911 (.A(n_126),
	.B(n_58),
	.C(n_172),
	.Y(n_221));
   OAI21X2 g3913 (.A0(n_185),
	.A1(n_174),
	.B0(n_173),
	.Y(n_220));
   AOI2BB2X1 g3915 (.A0N(n_123),
	.A1N(n_139),
	.B0(n_161),
	.B1(n_176),
	.Y(n_222));
   XNOR3X1 g3916 (.A(n_125),
	.B(n_143),
	.C(n_185),
	.Y(Z[2]));
   XNOR3X1 g3917 (.A(n_159),
	.B(n_165),
	.C(n_193),
	.Y(n_213));
   XOR3X1 g3919 (.A(n_56),
	.B(n_188),
	.C(n_167),
	.Y(n_217));
   XNOR3X1 g3920 (.A(n_50),
	.B(n_186),
	.C(n_164),
	.Y(n_216));
   BMXIX2 g3921 (.A(FE_OCPN3_n_103),
	.M0(n_128),
	.M1(n_48),
	.PPN(n_215),
	.S(n_24),
	.X2(n_162));
   ACHCONX2 g3927 (.A(n_133),
	.B(n_187),
	.CI(n_164),
	.CON(n_211));
   ACHCONX2 g3928 (.A(n_56),
	.B(n_189),
	.CI(n_167),
	.CON(n_210));
   INVX1 g3929 (.A(n_193),
	.Y(n_209));
   INVX1 g3932 (.A(n_5),
	.Y(n_207));
   OAI2BB2X1 g3933 (.A0N(n_150),
	.A1N(n_153),
	.B0(n_150),
	.B1(n_153),
	.Y(n_206));
   OAI22XL g3935 (.A0(n_178),
	.A1(n_182),
	.B0(n_179),
	.B1(n_183),
	.Y(n_205));
   AOI22X1 g3936 (.A0(n_126),
	.A1(n_155),
	.B0(n_47),
	.B1(n_156),
	.Y(n_204));
   OAI22XL g3937 (.A0(n_150),
	.A1(n_179),
	.B0(n_149),
	.B1(n_178),
	.Y(n_203));
   OAI22XL g3938 (.A0(n_131),
	.A1(n_180),
	.B0(n_49),
	.B1(n_181),
	.Y(n_202));
   ACHCONX2 g3939 (.A(n_48),
	.B(n_24),
	.CI(n_163),
	.CON(n_201));
   NOR2XL g3940 (.A(n_149),
	.B(n_153),
	.Y(n_200));
   NAND2X1 g3943 (.A(n_131),
	.B(n_181),
	.Y(n_197));
   NOR2XL g3944 (.A(n_55),
	.B(n_154),
	.Y(n_196));
   NAND2X1 g3945 (.A(n_149),
	.B(n_179),
	.Y(n_195));
   MXI2XL g3950 (.A(n_119),
	.B(n_120),
	.S0(n_136),
	.Y(n_193));
   INVX1 g3953 (.A(n_188),
	.Y(n_189));
   INVX1 g3954 (.A(n_186),
	.Y(n_187));
   INVX1 g3956 (.A(n_182),
	.Y(n_183));
   INVX1 g3957 (.A(n_180),
	.Y(n_181));
   INVX1 g3958 (.A(n_179),
	.Y(n_178));
   NAND2X1 g3960 (.A(n_123),
	.B(n_139),
	.Y(n_176));
   OAI22X1 g3961 (.A0(n_92),
	.A1(n_115),
	.B0(n_98),
	.B1(n_315),
	.Y(n_175));
   NOR2X1 g3962 (.A(n_125),
	.B(n_143),
	.Y(n_174));
   NAND2X1 g3963 (.A(n_125),
	.B(n_143),
	.Y(n_173));
   OAI21XL g3965 (.A0(n_64),
	.A1(n_117),
	.B0(B[7]),
	.Y(n_172));
   OAI22X2 g3966 (.A0(n_129),
	.A1(n_116),
	.B0(n_132),
	.B1(n_65),
	.Y(n_190));
   NAND2X1 g3967 (.A(n_118),
	.B(n_142),
	.Y(n_171));
   AOI21XL g3968 (.A0(n_315),
	.A1(n_115),
	.B0(n_28),
	.Y(n_188));
   OAI21XL g3969 (.A0(n_66),
	.A1(n_112),
	.B0(FE_OFN1_n_107),
	.Y(n_186));
   NAND2X1 g3970 (.A(n_96),
	.B(n_141),
	.Y(n_185));
   NOR2XL g3971 (.A(n_120),
	.B(n_136),
	.Y(n_184));
   OAI22XL g3972 (.A0(n_130),
	.A1(n_116),
	.B0(n_134),
	.B1(n_65),
	.Y(n_182));
   OAI22XL g3973 (.A0(n_87),
	.A1(n_115),
	.B0(n_28),
	.B1(n_315),
	.Y(n_180));
   AOI22X1 g3974 (.A0(n_86),
	.A1(n_114),
	.B0(n_82),
	.B1(n_62),
	.Y(n_170));
   OAI22X2 g3975 (.A0(n_68),
	.A1(n_113),
	.B0(n_73),
	.B1(n_2),
	.Y(n_179));
   INVX1 g3976 (.A(n_168),
	.Y(n_169));
   INVX1 g3977 (.A(n_165),
	.Y(n_166));
   INVX1 g3978 (.A(n_162),
	.Y(n_163));
   INVX1 g3979 (.A(n_160),
	.Y(n_161));
   INVX1 g3981 (.A(n_155),
	.Y(n_156));
   INVX1 g3983 (.A(n_152),
	.Y(n_151));
   INVX1 g3984 (.A(n_150),
	.Y(n_149));
   AOI22X1 g3985 (.A0(n_101),
	.A1(n_117),
	.B0(n_110),
	.B1(n_64),
	.Y(n_168));
   OAI22X2 g3986 (.A0(n_98),
	.A1(n_115),
	.B0(n_315),
	.B1(n_103),
	.Y(n_148));
   OAI22XL g3987 (.A0(n_73),
	.A1(n_113),
	.B0(n_97),
	.B1(n_2),
	.Y(n_167));
   OAI22X2 g3988 (.A0(n_61),
	.A1(n_113),
	.B0(n_67),
	.B1(n_2),
	.Y(n_165));
   AOI22X1 g3989 (.A0(n_106),
	.A1(n_117),
	.B0(n_109),
	.B1(n_64),
	.Y(n_164));
   AOI22X1 g3990 (.A0(n_111),
	.A1(n_117),
	.B0(n_101),
	.B1(n_64),
	.Y(n_162));
   AOI22X1 g3991 (.A0(n_90),
	.A1(n_117),
	.B0(n_102),
	.B1(n_64),
	.Y(n_147));
   AOI22X1 g3992 (.A0(n_105),
	.A1(n_114),
	.B0(n_81),
	.B1(n_62),
	.Y(n_160));
   AOI22X1 g3993 (.A0(n_69),
	.A1(n_112),
	.B0(n_99),
	.B1(n_66),
	.Y(n_146));
   AOI22X2 g3994 (.A0(n_104),
	.A1(n_114),
	.B0(n_105),
	.B1(n_62),
	.Y(n_159));
   AOI22X1 g3995 (.A0(n_81),
	.A1(n_114),
	.B0(n_86),
	.B1(n_62),
	.Y(n_145));
   OAI22XL g3996 (.A0(n_67),
	.A1(n_113),
	.B0(n_85),
	.B1(n_2),
	.Y(n_157));
   AOI22X1 g3997 (.A0(n_84),
	.A1(n_112),
	.B0(n_69),
	.B1(n_66),
	.Y(n_144));
   AOI22X1 g3998 (.A0(n_109),
	.A1(n_117),
	.B0(B[7]),
	.B1(n_64),
	.Y(n_155));
   OAI22XL g3999 (.A0(n_97),
	.A1(n_113),
	.B0(FE_OFN2_n_107),
	.B1(n_2),
	.Y(n_154));
   OAI22X2 g4000 (.A0(n_100),
	.A1(n_113),
	.B0(n_68),
	.B1(n_2),
	.Y(n_153));
   OAI22XL g4001 (.A0(n_134),
	.A1(n_116),
	.B0(n_127),
	.B1(n_65),
	.Y(n_152));
   OAI22X2 g4002 (.A0(n_83),
	.A1(n_115),
	.B0(n_87),
	.B1(n_315),
	.Y(n_150));
   OAI22X2 g4003 (.A0(n_53),
	.A1(n_76),
	.B0(n_43),
	.B1(n_72),
	.Y(n_143));
   OAI22XL g4005 (.A0(n_53),
	.A1(n_107),
	.B0(n_43),
	.B1(n_74),
	.Y(n_142));
   OAI22X2 g4007 (.A0(n_53),
	.A1(n_95),
	.B0(n_43),
	.B1(n_76),
	.Y(n_141));
   AOI22X1 g4008 (.A0(n_54),
	.A1(n_71),
	.B0(B[0]),
	.B1(n_77),
	.Y(n_140));
   AOI22X2 g4010 (.A0(n_54),
	.A1(n_70),
	.B0(B[0]),
	.B1(n_108),
	.Y(n_139));
   INVX1 g4011 (.A(n_138),
	.Y(n_137));
   AOI2BB2X2 g4012 (.A0N(n_43),
	.A1N(n_24),
	.B0(n_54),
	.B1(n_75),
	.Y(n_138));
   AOI22X1 g4013 (.A0(n_54),
	.A1(n_80),
	.B0(B[0]),
	.B1(n_70),
	.Y(n_136));
   OAI22X2 g4014 (.A0(n_53),
	.A1(n_78),
	.B0(n_43),
	.B1(n_79),
	.Y(n_135));
   INVX1 g4015 (.A(n_88),
	.Y(n_134));
   INVX1 g4016 (.A(n_50),
	.Y(n_133));
   INVX1 g4017 (.A(n_111),
	.Y(n_132));
   INVX1 g4018 (.A(n_49),
	.Y(n_131));
   INVX1 g4019 (.A(n_110),
	.Y(n_130));
   INVX1 g4021 (.A(n_102),
	.Y(n_129));
   INVX1 g4022 (.A(n_48),
	.Y(n_128));
   INVX1 g4023 (.A(n_106),
	.Y(n_127));
   INVX1 g4024 (.A(n_47),
	.Y(n_126));
   INVX1 g4026 (.A(n_122),
	.Y(n_123));
   NOR2XL g4027 (.A(n_42),
	.B(n_315),
	.Y(n_125));
   AOI211X2 g4028 (.A0(A[0]),
	.A1(B[2]),
	.B0(n_28),
	.C0(n_94),
	.Y(n_124));
   NOR2X2 g4029 (.A(n_42),
	.B(n_2),
	.Y(n_121));
   NOR2X1 g4030 (.A(n_42),
	.B(n_65),
	.Y(n_122));
   INVX1 g4031 (.A(n_119),
	.Y(n_120));
   INVX3 g4033 (.A(n_117),
	.Y(n_116));
   INVX2 g4034 (.A(n_115),
	.Y(n_114));
   INVX1 g4035 (.A(n_113),
	.Y(n_112));
   AOI211X2 g4036 (.A0(A[0]),
	.A1(B[4]),
	.B0(FE_OFN2_n_107),
	.C0(n_93),
	.Y(n_119));
   AOI211X1 g4037 (.A0(A[0]),
	.A1(B[6]),
	.B0(n_41),
	.C0(n_89),
	.Y(n_118));
   CLKAND2X6 g4038 (.A(n_60),
	.B(n_65),
	.Y(n_117));
   NAND2X6 g4039 (.A(n_59),
	.B(n_315),
	.Y(n_115));
   NAND2X4 g4040 (.A(n_91),
	.B(n_2),
	.Y(n_113));
   INVX1 g4041 (.A(n_107),
	.Y(n_108));
   INVX1 g4042 (.A(n_103),
	.Y(n_104));
   INVX1 g4043 (.A(n_99),
	.Y(n_100));
   AOI22X1 g4045 (.A0(A[0]),
	.A1(n_24),
	.B0(n_42),
	.B1(FE_OCPN3_n_103),
	.Y(n_95));
   AOI21X1 g4046 (.A0(n_42),
	.A1(n_30),
	.B0(n_24),
	.Y(n_94));
   AOI21XL g4047 (.A0(n_42),
	.A1(n_32),
	.B0(n_28),
	.Y(n_93));
   AOI22X1 g4048 (.A0(A[0]),
	.A1(n_28),
	.B0(n_42),
	.B1(FE_OFN0_n_105),
	.Y(n_92));
   AOI22X2 g4049 (.A0(n_32),
	.A1(n_34),
	.B0(B[4]),
	.B1(FE_OFN1_n_107),
	.Y(n_91));
   OAI22XL g4050 (.A0(n_42),
	.A1(B[7]),
	.B0(A[0]),
	.B1(n_41),
	.Y(n_90));
   AOI21XL g4051 (.A0(n_42),
	.A1(n_46),
	.B0(n_34),
	.Y(n_89));
   AOI2BB1X1 g4052 (.A0N(A[5]),
	.A1N(B[7]),
	.B0(n_50),
	.Y(n_88));
   AOI21X1 g4053 (.A0(n_45),
	.A1(n_41),
	.B0(n_49),
	.Y(n_111));
   AOI2BB1X1 g4054 (.A0N(A[4]),
	.A1N(B[7]),
	.B0(n_55),
	.Y(n_110));
   AOI2BB1X1 g4055 (.A0N(A[7]),
	.A1N(B[7]),
	.B0(n_58),
	.Y(n_109));
   MX2XL g4056 (.A(FE_OCPN3_n_103),
	.B(n_24),
	.S0(n_44),
	.Y(n_107));
   AOI2BB1X1 g4057 (.A0N(A[6]),
	.A1N(B[7]),
	.B0(n_47),
	.Y(n_106));
   OAI22X1 g4058 (.A0(n_36),
	.A1(FE_OFN0_n_105),
	.B0(A[3]),
	.B1(n_28),
	.Y(n_105));
   AOI22X1 g4059 (.A0(A[2]),
	.A1(n_28),
	.B0(n_45),
	.B1(FE_OFN0_n_105),
	.Y(n_103));
   AOI21X2 g4060 (.A0(n_38),
	.A1(n_41),
	.B0(n_48),
	.Y(n_102));
   AOI21XL g4061 (.A0(n_36),
	.A1(n_41),
	.B0(n_56),
	.Y(n_101));
   OAI22X1 g4062 (.A0(n_39),
	.A1(FE_OFN1_n_107),
	.B0(A[4]),
	.B1(FE_OFN2_n_107),
	.Y(n_99));
   AOI22X1 g4063 (.A0(A[1]),
	.A1(n_28),
	.B0(n_38),
	.B1(FE_OFN0_n_105),
	.Y(n_98));
   AOI22X1 g4064 (.A0(A[7]),
	.A1(FE_OFN2_n_107),
	.B0(n_40),
	.B1(FE_OFN1_n_107),
	.Y(n_97));
   AND2X1 g4065 (.A(FE_OCPN3_n_103),
	.B(n_51),
	.Y(n_96));
   INVX1 g4066 (.A(n_84),
	.Y(n_85));
   INVX1 g4067 (.A(n_82),
	.Y(n_83));
   INVX1 g4068 (.A(n_79),
	.Y(n_80));
   INVX1 g4069 (.A(n_77),
	.Y(n_78));
   INVX1 g4070 (.A(n_74),
	.Y(n_75));
   INVX1 g4071 (.A(n_71),
	.Y(n_72));
   INVX1 g4073 (.A(n_65),
	.Y(n_64));
   INVX1 g4074 (.A(n_315),
	.Y(n_62));
   AOI22X1 g4075 (.A0(A[0]),
	.A1(FE_OFN2_n_107),
	.B0(n_42),
	.B1(FE_OFN1_n_107),
	.Y(n_61));
   AOI22X2 g4076 (.A0(n_46),
	.A1(n_41),
	.B0(B[6]),
	.B1(B[7]),
	.Y(n_60));
   AOI22X2 g4077 (.A0(n_30),
	.A1(n_28),
	.B0(B[2]),
	.B1(FE_OFN0_n_105),
	.Y(n_59));
   AOI22X1 g4078 (.A0(A[7]),
	.A1(n_28),
	.B0(n_40),
	.B1(FE_OFN0_n_105),
	.Y(n_87));
   OAI22XL g4079 (.A0(n_37),
	.A1(FE_OFN0_n_105),
	.B0(A[5]),
	.B1(n_28),
	.Y(n_86));
   OAI22X1 g4080 (.A0(n_45),
	.A1(FE_OFN1_n_107),
	.B0(A[2]),
	.B1(FE_OFN2_n_107),
	.Y(n_84));
   OAI22XL g4081 (.A0(n_44),
	.A1(FE_OFN0_n_105),
	.B0(A[6]),
	.B1(n_28),
	.Y(n_82));
   OAI22XL g4082 (.A0(n_39),
	.A1(FE_OFN0_n_105),
	.B0(A[4]),
	.B1(n_28),
	.Y(n_81));
   AOI22X2 g4083 (.A0(A[4]),
	.A1(n_24),
	.B0(n_39),
	.B1(FE_OCPN3_n_103),
	.Y(n_79));
   OAI22X2 g4084 (.A0(n_36),
	.A1(FE_OCPN3_n_103),
	.B0(A[3]),
	.B1(n_24),
	.Y(n_77));
   AOI22X2 g4085 (.A0(A[1]),
	.A1(n_24),
	.B0(n_38),
	.B1(FE_OCPN3_n_103),
	.Y(n_76));
   CLKMX2X2 g4086 (.A(FE_OCPN3_n_103),
	.B(n_24),
	.S0(n_40),
	.Y(n_74));
   AOI22X1 g4087 (.A0(A[6]),
	.A1(FE_OFN2_n_107),
	.B0(n_44),
	.B1(FE_OFN1_n_107),
	.Y(n_73));
   OAI22X2 g4088 (.A0(n_45),
	.A1(FE_OCPN3_n_103),
	.B0(A[2]),
	.B1(n_24),
	.Y(n_71));
   OAI22X1 g4089 (.A0(n_37),
	.A1(FE_OCPN3_n_103),
	.B0(A[5]),
	.B1(n_24),
	.Y(n_70));
   OAI22XL g4090 (.A0(n_36),
	.A1(FE_OFN1_n_107),
	.B0(A[3]),
	.B1(FE_OFN2_n_107),
	.Y(n_69));
   AOI22X1 g4091 (.A0(A[5]),
	.A1(FE_OFN2_n_107),
	.B0(n_37),
	.B1(FE_OFN1_n_107),
	.Y(n_68));
   AOI22X1 g4092 (.A0(A[1]),
	.A1(FE_OFN2_n_107),
	.B0(n_38),
	.B1(FE_OFN1_n_107),
	.Y(n_67));
   OA22X4 g4094 (.A0(B[5]),
	.A1(n_46),
	.B0(B[6]),
	.B1(n_34),
	.Y(n_65));
   INVX4 g4096 (.A(n_54),
	.Y(n_53));
   NOR2XL g4098 (.A(n_40),
	.B(n_41),
	.Y(n_58));
   NOR2XL g4099 (.A(n_42),
	.B(n_41),
	.Y(n_57));
   NOR2XL g4100 (.A(n_36),
	.B(n_41),
	.Y(n_56));
   NOR2XL g4101 (.A(n_39),
	.B(n_41),
	.Y(n_55));
   CLKAND2X6 g4102 (.A(n_43),
	.B(FE_OCPN3_n_103),
	.Y(n_54));
   INVX1 g4103 (.A(n_51),
	.Y(Z[0]));
   NAND2X1 g4105 (.A(A[0]),
	.B(B[0]),
	.Y(n_51));
   NOR2XL g4106 (.A(n_37),
	.B(n_41),
	.Y(n_50));
   NOR2X1 g4107 (.A(n_45),
	.B(n_41),
	.Y(n_49));
   NOR2X2 g4108 (.A(n_38),
	.B(n_41),
	.Y(n_48));
   NOR2XL g4109 (.A(n_44),
	.B(n_41),
	.Y(n_47));
   INVX1 g4110 (.A(B[6]),
	.Y(n_46));
   INVX1 g4118 (.A(B[4]),
	.Y(n_32));
   INVX1 g4123 (.A(B[2]),
	.Y(n_30));
   INVX1 g4125 (.A(A[2]),
	.Y(n_45));
   INVX1 g4126 (.A(A[6]),
	.Y(n_44));
   INVX4 g4127 (.A(B[0]),
	.Y(n_43));
   INVX1 g4128 (.A(A[0]),
	.Y(n_42));
   CLKINVX8 g4129 (.A(B[7]),
	.Y(n_41));
   INVX1 g4130 (.A(A[7]),
	.Y(n_40));
   INVX1 g4131 (.A(A[4]),
	.Y(n_39));
   INVX1 g4132 (.A(A[1]),
	.Y(n_38));
   INVX1 g4133 (.A(A[5]),
	.Y(n_37));
   INVX1 g4134 (.A(A[3]),
	.Y(n_36));
   INVX4 g4177 (.A(FE_OCPN3_n_103),
	.Y(n_24));
   AOI2BB1X1 g2 (.A0N(n_269),
	.A1N(n_281),
	.B0(n_270),
	.Y(n_23));
   XOR3X1 g4181 (.A(n_221),
	.B(n_313),
	.C(n_294),
	.Y(Z[15]));
   AND2X1 g4182 (.A(n_271),
	.B(n_283),
	.Y(n_21));
   XNOR3X1 g4183 (.A(n_262),
	.B(n_256),
	.C(n_21),
	.Y(Z[9]));
   XNOR3X1 g4184 (.A(n_319),
	.B(n_17),
	.C(n_281),
	.Y(Z[7]));
   MXI2XL g4185 (.A(n_217),
	.B(n_232),
	.S0(n_251),
	.Y(n_18));
   MXI2X1 g4186 (.A(n_235),
	.B(n_234),
	.S0(n_14),
	.Y(n_17));
   MXI2XL g4187 (.A(n_210),
	.B(n_231),
	.S0(n_12),
	.Y(n_16));
   MXI2XL g4189 (.A(n_5),
	.B(n_207),
	.S0(n_222),
	.Y(n_14));
   XNOR3X1 g4190 (.A(n_3),
	.B(n_230),
	.C(n_255),
	.Y(Z[4]));
   MXI2XL g4191 (.A(n_152),
	.B(n_151),
	.S0(n_6),
	.Y(n_12));
   MXI2X1 g4192 (.A(n_316),
	.B(n_229),
	.S0(n_206),
	.Y(n_11));
   MXI2XL g4193 (.A(n_201),
	.B(n_233),
	.S0(n_203),
	.Y(n_10));
   MXI2XL g4194 (.A(n_168),
	.B(n_169),
	.S0(n_202),
	.Y(n_9));
   MXI2XL g4195 (.A(n_160),
	.B(n_161),
	.S0(n_4),
	.Y(n_8));
   OA21X1 g4196 (.A0(n_96),
	.A1(n_141),
	.B0(n_185),
	.Y(Z[1]));
   CLKXOR2X1 g4197 (.A(n_55),
	.B(n_154),
	.Y(n_6));
   CLKXOR2X1 g4198 (.A(n_118),
	.B(n_142),
	.Y(n_5));
   MXI2X1 g4199 (.A(n_122),
	.B(n_123),
	.S0(n_139),
	.Y(n_4));
   NOR2BX1 g4200 (.AN(n_124),
	.B(n_140),
	.Y(n_3));
   CLKMX2X4 g4201 (.A(n_28),
	.B(B[3]),
	.S0(B[4]),
	.Y(n_2));
   ADDFX1 g4204 (.A(n_178),
	.B(n_183),
	.CI(n_228),
	.CO(n_312),
	.S(UNCONNECTED0));
   ADDFX1 g4205 (.A(n_126),
	.B(n_156),
	.CI(n_211),
	.CO(n_313),
	.S(UNCONNECTED1));
   XOR3XL g4206 (.A(n_190),
	.B(n_57),
	.C(n_138),
	.Y(n_314));
   XNOR2X4 g4207 (.A(B[1]),
	.B(B[2]),
	.Y(n_315));
   ADDFX1 g4208 (.A(n_57),
	.B(n_137),
	.CI(n_190),
	.CO(n_316),
	.S(UNCONNECTED2));
   ADDFHX1 g4209 (.A(n_157),
	.B(n_184),
	.CI(n_8),
	.CO(n_318),
	.S(n_317));
   INVXL g3 (.A(n_318),
	.Y(n_319));
endmodule

module simple_mac (
	clk, 
	rst_n, 
	cf_we, 
	cf_addr, 
	cf_din, 
	start, 
	din, 
	coef_sel, 
	clr_acc, 
	acc_out, 
	done, 
	busy);
   input clk;
   input rst_n;
   input cf_we;
   input [1:0] cf_addr;
   input [7:0] cf_din;
   input start;
   input [7:0] din;
   input [1:0] coef_sel;
   input clr_acc;
   output [15:0] acc_out;
   output done;
   output busy;

   // Internal wires
   wire [15:0] mult_result;
   wire [7:0] \coef[2] ;
   wire [7:0] \coef[0] ;
   wire [7:0] \coef[1] ;
   wire [7:0] \coef[3] ;
   wire [1:0] state;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;

   add_unsigned add_61_40 (.A(acc_out),
	.B(mult_result),
	.Z({ n_125,
		n_124,
		n_123,
		n_122,
		n_121,
		n_120,
		n_119,
		n_118,
		n_117,
		n_116,
		n_115,
		n_114,
		n_113,
		n_112,
		n_111,
		n_110 }));
   mult_unsigned mul_58_40 (.A(din),
	.B({ n_109,
		n_108,
		n_107,
		n_106,
		n_105,
		n_104,
		n_103,
		n_102 }),
	.Z({ n_139,
		n_140,
		n_141,
		n_142,
		n_143,
		n_144,
		n_145,
		n_146,
		n_147,
		n_148,
		n_149,
		n_150,
		n_151,
		n_152,
		n_153,
		n_154 }));
   INVX1 g414 (.A(start),
	.Y(n_99));
   NAND2X4 g707 (.A(n_93),
	.B(n_98),
	.Y(n_103));
   NAND2X2 g708 (.A(n_95),
	.B(n_85),
	.Y(n_108));
   OR2X6 g709 (.A(n_91),
	.B(n_96),
	.Y(n_109));
   NAND2X2 g710 (.A(n_89),
	.B(n_92),
	.Y(n_106));
   NAND2X2 g711 (.A(n_90),
	.B(n_87),
	.Y(n_105));
   OR2X1 g712 (.A(n_94),
	.B(n_84),
	.Y(n_107));
   NAND2X2 g713 (.A(n_86),
	.B(n_88),
	.Y(n_102));
   NAND2X2 g714 (.A(n_97),
	.B(n_83),
	.Y(n_104));
   AOI21X4 g715 (.A0(\coef[2] [1]),
	.A1(n_78),
	.B0(n_66),
	.Y(n_98));
   AOI22X2 g716 (.A0(\coef[0] [2]),
	.A1(n_82),
	.B0(\coef[1] [2]),
	.B1(n_76),
	.Y(n_97));
   OAI22X1 g717 (.A0(n_100),
	.A1(n_77),
	.B0(n_71),
	.B1(n_80),
	.Y(n_96));
   AOI22X2 g718 (.A0(\coef[2] [6]),
	.A1(n_78),
	.B0(\coef[3] [6]),
	.B1(n_79),
	.Y(n_95));
   OAI22X1 g719 (.A0(n_68),
	.A1(n_81),
	.B0(n_74),
	.B1(n_75),
	.Y(n_94));
   AOI22X4 g720 (.A0(\coef[0] [1]),
	.A1(n_82),
	.B0(\coef[1] [1]),
	.B1(n_76),
	.Y(n_93));
   AOI22X2 g721 (.A0(\coef[2] [4]),
	.A1(n_78),
	.B0(\coef[3] [4]),
	.B1(n_79),
	.Y(n_92));
   OAI22X1 g722 (.A0(n_72),
	.A1(n_81),
	.B0(n_70),
	.B1(n_75),
	.Y(n_91));
   AOI22X4 g723 (.A0(\coef[0] [3]),
	.A1(n_82),
	.B0(\coef[1] [3]),
	.B1(n_76),
	.Y(n_90));
   AOI22X1 g724 (.A0(\coef[0] [4]),
	.A1(n_82),
	.B0(\coef[1] [4]),
	.B1(n_76),
	.Y(n_89));
   AOI22X1 g725 (.A0(\coef[0] [0]),
	.A1(n_82),
	.B0(\coef[1] [0]),
	.B1(n_76),
	.Y(n_88));
   AOI21X4 g726 (.A0(\coef[2] [3]),
	.A1(n_78),
	.B0(n_64),
	.Y(n_87));
   AOI22X1 g727 (.A0(\coef[2] [0]),
	.A1(n_78),
	.B0(\coef[3] [0]),
	.B1(n_79),
	.Y(n_86));
   AOI22X1 g728 (.A0(\coef[0] [6]),
	.A1(n_82),
	.B0(\coef[1] [6]),
	.B1(n_76),
	.Y(n_85));
   OAI22X2 g729 (.A0(n_101),
	.A1(n_77),
	.B0(n_69),
	.B1(n_80),
	.Y(n_84));
   AOI21X2 g730 (.A0(\coef[2] [2]),
	.A1(n_78),
	.B0(n_65),
	.Y(n_83));
   INVX1 g734 (.A(n_82),
	.Y(n_81));
   INVX2 g735 (.A(n_80),
	.Y(n_79));
   NOR2X8 g736 (.A(coef_sel[0]),
	.B(coef_sel[1]),
	.Y(n_82));
   NAND2X6 g737 (.A(coef_sel[0]),
	.B(coef_sel[1]),
	.Y(n_80));
   INVX2 g738 (.A(n_78),
	.Y(n_77));
   INVX1 g739 (.A(n_76),
	.Y(n_75));
   NOR2X6 g740 (.A(coef_sel[0]),
	.B(n_73),
	.Y(n_78));
   NOR2X8 g741 (.A(coef_sel[1]),
	.B(n_67),
	.Y(n_76));
   CLKINVX8 g744 (.A(coef_sel[1]),
	.Y(n_73));
   CLKINVX8 g752 (.A(coef_sel[0]),
	.Y(n_67));
   NOR2BX4 g2 (.AN(\coef[3] [1]),
	.B(n_80),
	.Y(n_66));
   NOR2BX1 g753 (.AN(\coef[3] [2]),
	.B(n_80),
	.Y(n_65));
   NOR2BX1 g754 (.AN(\coef[3] [3]),
	.B(n_80),
	.Y(n_64));
   SDFFRHQX4 \coef_reg[0][0]  (.CK(clk),
	.D(cf_din[0]),
	.Q(\coef[0] [0]),
	.RN(rst_n),
	.SE(n_46),
	.SI(\coef[0] [0]));
   SDFFRHQX4 \coef_reg[0][1]  (.CK(clk),
	.D(cf_din[1]),
	.Q(\coef[0] [1]),
	.RN(rst_n),
	.SE(n_46),
	.SI(\coef[0] [1]));
   SDFFRHQX4 \coef_reg[0][2]  (.CK(clk),
	.D(cf_din[2]),
	.Q(\coef[0] [2]),
	.RN(rst_n),
	.SE(n_46),
	.SI(\coef[0] [2]));
   SDFFRHQX4 \coef_reg[0][3]  (.CK(clk),
	.D(cf_din[3]),
	.Q(\coef[0] [3]),
	.RN(rst_n),
	.SE(n_46),
	.SI(\coef[0] [3]));
   SDFFRHQX4 \coef_reg[0][4]  (.CK(clk),
	.D(cf_din[4]),
	.Q(\coef[0] [4]),
	.RN(rst_n),
	.SE(n_46),
	.SI(\coef[0] [4]));
   SDFFRHQX4 \coef_reg[0][6]  (.CK(clk),
	.D(cf_din[6]),
	.Q(\coef[0] [6]),
	.RN(rst_n),
	.SE(n_46),
	.SI(\coef[0] [6]));
   SDFFRHQX4 \coef_reg[1][0]  (.CK(clk),
	.D(cf_din[0]),
	.Q(\coef[1] [0]),
	.RN(rst_n),
	.SE(n_43),
	.SI(\coef[1] [0]));
   SDFFRHQX4 \coef_reg[1][1]  (.CK(clk),
	.D(cf_din[1]),
	.Q(\coef[1] [1]),
	.RN(rst_n),
	.SE(n_43),
	.SI(\coef[1] [1]));
   SDFFRHQX4 \coef_reg[1][2]  (.CK(clk),
	.D(cf_din[2]),
	.Q(\coef[1] [2]),
	.RN(rst_n),
	.SE(n_43),
	.SI(\coef[1] [2]));
   SDFFRHQX4 \coef_reg[1][3]  (.CK(clk),
	.D(cf_din[3]),
	.Q(\coef[1] [3]),
	.RN(rst_n),
	.SE(n_43),
	.SI(\coef[1] [3]));
   SDFFRHQX4 \coef_reg[1][4]  (.CK(clk),
	.D(cf_din[4]),
	.Q(\coef[1] [4]),
	.RN(rst_n),
	.SE(n_43),
	.SI(\coef[1] [4]));
   SDFFRHQX4 \coef_reg[1][6]  (.CK(clk),
	.D(cf_din[6]),
	.Q(\coef[1] [6]),
	.RN(rst_n),
	.SE(n_43),
	.SI(\coef[1] [6]));
   SDFFRHQX4 \coef_reg[2][0]  (.CK(clk),
	.D(cf_din[0]),
	.Q(\coef[2] [0]),
	.RN(rst_n),
	.SE(n_44),
	.SI(\coef[2] [0]));
   SDFFRHQX4 \coef_reg[2][1]  (.CK(clk),
	.D(cf_din[1]),
	.Q(\coef[2] [1]),
	.RN(rst_n),
	.SE(n_44),
	.SI(\coef[2] [1]));
   SDFFRHQX4 \coef_reg[2][2]  (.CK(clk),
	.D(cf_din[2]),
	.Q(\coef[2] [2]),
	.RN(rst_n),
	.SE(n_44),
	.SI(\coef[2] [2]));
   SDFFRHQX4 \coef_reg[2][3]  (.CK(clk),
	.D(cf_din[3]),
	.Q(\coef[2] [3]),
	.RN(rst_n),
	.SE(n_44),
	.SI(\coef[2] [3]));
   SDFFRHQX4 \coef_reg[2][4]  (.CK(clk),
	.D(cf_din[4]),
	.Q(\coef[2] [4]),
	.RN(rst_n),
	.SE(n_44),
	.SI(\coef[2] [4]));
   SDFFRHQX4 \coef_reg[2][6]  (.CK(clk),
	.D(cf_din[6]),
	.Q(\coef[2] [6]),
	.RN(rst_n),
	.SE(n_44),
	.SI(\coef[2] [6]));
   SDFFRHQX4 \coef_reg[3][0]  (.CK(clk),
	.D(cf_din[0]),
	.Q(\coef[3] [0]),
	.RN(rst_n),
	.SE(n_45),
	.SI(\coef[3] [0]));
   SDFFRHQX4 \coef_reg[3][1]  (.CK(clk),
	.D(cf_din[1]),
	.Q(\coef[3] [1]),
	.RN(rst_n),
	.SE(n_45),
	.SI(\coef[3] [1]));
   SDFFRHQX4 \coef_reg[3][2]  (.CK(clk),
	.D(cf_din[2]),
	.Q(\coef[3] [2]),
	.RN(rst_n),
	.SE(n_45),
	.SI(\coef[3] [2]));
   SDFFRHQX4 \coef_reg[3][3]  (.CK(clk),
	.D(cf_din[3]),
	.Q(\coef[3] [3]),
	.RN(rst_n),
	.SE(n_45),
	.SI(\coef[3] [3]));
   SDFFRHQX4 \coef_reg[3][4]  (.CK(clk),
	.D(cf_din[4]),
	.Q(\coef[3] [4]),
	.RN(rst_n),
	.SE(n_45),
	.SI(\coef[3] [4]));
   SDFFRHQX4 \coef_reg[3][6]  (.CK(clk),
	.D(cf_din[6]),
	.Q(\coef[3] [6]),
	.RN(rst_n),
	.SE(n_45),
	.SI(\coef[3] [6]));
   SDFFRHQX4 \mult_result_reg[0]  (.CK(clk),
	.D(n_154),
	.Q(mult_result[0]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[0]));
   SDFFRHQX4 \mult_result_reg[1]  (.CK(clk),
	.D(n_153),
	.Q(mult_result[1]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[1]));
   SDFFRHQX4 \mult_result_reg[2]  (.CK(clk),
	.D(n_152),
	.Q(mult_result[2]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[2]));
   SDFFRHQX4 \mult_result_reg[3]  (.CK(clk),
	.D(n_151),
	.Q(mult_result[3]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[3]));
   SDFFRHQX4 \mult_result_reg[4]  (.CK(clk),
	.D(n_150),
	.Q(mult_result[4]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[4]));
   SDFFRHQX4 \mult_result_reg[5]  (.CK(clk),
	.D(n_149),
	.Q(mult_result[5]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[5]));
   SDFFRHQX4 \mult_result_reg[6]  (.CK(clk),
	.D(n_148),
	.Q(mult_result[6]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[6]));
   SDFFRHQX4 \mult_result_reg[7]  (.CK(clk),
	.D(n_147),
	.Q(mult_result[7]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[7]));
   SDFFRHQX4 \mult_result_reg[8]  (.CK(clk),
	.D(n_146),
	.Q(mult_result[8]),
	.RN(rst_n),
	.SE(n_39),
	.SI(mult_result[8]));
   SDFFRHQX1 \mult_result_reg[9]  (.CK(clk),
	.D(mult_result[9]),
	.Q(mult_result[9]),
	.RN(rst_n),
	.SE(n_38),
	.SI(n_145));
   SDFFRHQX1 \mult_result_reg[10]  (.CK(clk),
	.D(mult_result[10]),
	.Q(mult_result[10]),
	.RN(rst_n),
	.SE(n_38),
	.SI(n_144));
   SDFFRHQX1 \mult_result_reg[11]  (.CK(clk),
	.D(mult_result[11]),
	.Q(mult_result[11]),
	.RN(rst_n),
	.SE(n_38),
	.SI(n_143));
   SDFFRHQX1 \mult_result_reg[12]  (.CK(clk),
	.D(mult_result[12]),
	.Q(mult_result[12]),
	.RN(rst_n),
	.SE(n_38),
	.SI(n_142));
   SDFFRHQX1 \mult_result_reg[13]  (.CK(clk),
	.D(mult_result[13]),
	.Q(mult_result[13]),
	.RN(rst_n),
	.SE(n_38),
	.SI(n_141));
   SDFFRHQX1 \mult_result_reg[14]  (.CK(clk),
	.D(mult_result[14]),
	.Q(mult_result[14]),
	.RN(rst_n),
	.SE(n_38),
	.SI(n_140));
   SDFFRHQX1 \mult_result_reg[15]  (.CK(clk),
	.D(mult_result[15]),
	.Q(mult_result[15]),
	.RN(rst_n),
	.SE(n_38),
	.SI(n_139));
   OAI22XL g849 (.A0(n_14),
	.A1(n_1),
	.B0(n_21),
	.B1(n_40),
	.Y(n_63));
   OAI22XL g850 (.A0(n_5),
	.A1(n_1),
	.B0(n_40),
	.B1(n_18),
	.Y(n_62));
   OAI22XL g851 (.A0(n_12),
	.A1(n_1),
	.B0(n_40),
	.B1(n_24),
	.Y(n_61));
   OAI22XL g852 (.A0(n_10),
	.A1(n_1),
	.B0(n_40),
	.B1(n_23),
	.Y(n_60));
   OAI22XL g853 (.A0(n_27),
	.A1(n_1),
	.B0(n_40),
	.B1(n_37),
	.Y(n_59));
   OAI22XL g854 (.A0(n_26),
	.A1(n_1),
	.B0(n_40),
	.B1(n_32),
	.Y(n_58));
   OAI22XL g855 (.A0(n_30),
	.A1(n_1),
	.B0(n_40),
	.B1(n_17),
	.Y(n_57));
   OAI22XL g856 (.A0(n_9),
	.A1(n_1),
	.B0(n_40),
	.B1(n_22),
	.Y(n_56));
   OAI22XL g857 (.A0(n_13),
	.A1(n_1),
	.B0(n_40),
	.B1(n_33),
	.Y(n_55));
   OAI22XL g858 (.A0(n_11),
	.A1(n_1),
	.B0(n_40),
	.B1(n_20),
	.Y(n_54));
   OAI22XL g859 (.A0(n_8),
	.A1(n_1),
	.B0(n_40),
	.B1(n_19),
	.Y(n_53));
   OAI22XL g860 (.A0(n_6),
	.A1(n_1),
	.B0(n_40),
	.B1(n_35),
	.Y(n_52));
   OAI22X1 g861 (.A0(n_7),
	.A1(n_1),
	.B0(n_40),
	.B1(n_15),
	.Y(n_51));
   OAI22XL g862 (.A0(n_29),
	.A1(n_1),
	.B0(n_34),
	.B1(n_40),
	.Y(n_50));
   OAI22XL g863 (.A0(n_28),
	.A1(n_1),
	.B0(n_36),
	.B1(n_40),
	.Y(n_49));
   OAI22XL g864 (.A0(n_31),
	.A1(n_1),
	.B0(n_40),
	.B1(n_16),
	.Y(n_48));
   ACHCONX2 g867 (.A(n_4),
	.B(n_2),
	.CI(n_25),
	.CON(n_47));
   NAND2X1 g869 (.A(n_3),
	.B(n_0),
	.Y(n_46));
   NAND3X1 g870 (.A(cf_addr[0]),
	.B(cf_we),
	.C(cf_addr[1]),
	.Y(n_45));
   NAND2X1 g871 (.A(cf_addr[1]),
	.B(n_0),
	.Y(n_44));
   NAND2X1 g872 (.A(n_40),
	.B(n_39),
	.Y(n_42));
   OAI21XL g873 (.A0(state[0]),
	.A1(n_99),
	.B0(n_40),
	.Y(n_41));
   NAND3X1 g875 (.A(cf_addr[0]),
	.B(cf_we),
	.C(n_3),
	.Y(n_43));
   INVX1 g877 (.A(n_39),
	.Y(n_38));
   NAND2X1 g878 (.A(busy),
	.B(n_25),
	.Y(n_40));
   NAND2X1 g879 (.A(n_2),
	.B(state[0]),
	.Y(n_39));
   INVX1 g880 (.A(n_117),
	.Y(n_37));
   INVX1 g881 (.A(n_111),
	.Y(n_36));
   INVX1 g882 (.A(n_124),
	.Y(n_35));
   INVX1 g883 (.A(n_110),
	.Y(n_34));
   INVX1 g884 (.A(n_121),
	.Y(n_33));
   INVX1 g885 (.A(n_118),
	.Y(n_32));
   INVX1 g899 (.A(n_113),
	.Y(n_24));
   INVX1 g900 (.A(n_116),
	.Y(n_23));
   INVX1 g901 (.A(n_120),
	.Y(n_22));
   INVX1 g902 (.A(n_112),
	.Y(n_21));
   INVX1 g903 (.A(n_122),
	.Y(n_20));
   INVX1 g904 (.A(n_123),
	.Y(n_19));
   INVX1 g905 (.A(n_115),
	.Y(n_18));
   INVX1 g906 (.A(n_119),
	.Y(n_17));
   INVX1 g907 (.A(n_114),
	.Y(n_16));
   INVX1 g908 (.A(n_125),
	.Y(n_15));
   INVX1 g921 (.A(cf_addr[1]),
	.Y(n_3));
   NAND2BX1 g755 (.AN(clr_acc),
	.B(n_40),
	.Y(n_1));
   NOR2BX1 g922 (.AN(cf_we),
	.B(cf_addr[0]),
	.Y(n_0));
   SDFFRXL \coef_reg[2][5]  (.CK(clk),
	.D(cf_din[5]),
	.Q(\coef[2] [5]),
	.QN(n_101),
	.RN(rst_n),
	.SE(n_44),
	.SI(\coef[2] [5]));
   SDFFRXL \coef_reg[2][7]  (.CK(clk),
	.D(cf_din[7]),
	.Q(\coef[2] [7]),
	.QN(n_100),
	.RN(rst_n),
	.SE(n_44),
	.SI(\coef[2] [7]));
   SDFFRXL \coef_reg[1][5]  (.CK(clk),
	.D(cf_din[5]),
	.Q(\coef[1] [5]),
	.QN(n_74),
	.RN(rst_n),
	.SE(n_43),
	.SI(\coef[1] [5]));
   SDFFRXL \coef_reg[0][7]  (.CK(clk),
	.D(cf_din[7]),
	.Q(\coef[0] [7]),
	.QN(n_72),
	.RN(rst_n),
	.SE(n_46),
	.SI(\coef[0] [7]));
   SDFFRXL \coef_reg[3][7]  (.CK(clk),
	.D(cf_din[7]),
	.Q(\coef[3] [7]),
	.QN(n_71),
	.RN(rst_n),
	.SE(n_45),
	.SI(\coef[3] [7]));
   SDFFRXL \coef_reg[1][7]  (.CK(clk),
	.D(cf_din[7]),
	.Q(\coef[1] [7]),
	.QN(n_70),
	.RN(rst_n),
	.SE(n_43),
	.SI(\coef[1] [7]));
   SDFFRXL \coef_reg[3][5]  (.CK(clk),
	.D(cf_din[5]),
	.Q(\coef[3] [5]),
	.QN(n_69),
	.RN(rst_n),
	.SE(n_45),
	.SI(\coef[3] [5]));
   SDFFRXL \coef_reg[0][5]  (.CK(clk),
	.D(cf_din[5]),
	.Q(\coef[0] [5]),
	.QN(n_68),
	.RN(rst_n),
	.SE(n_46),
	.SI(\coef[0] [5]));
   DFFRXL \acc_out_reg[4]  (.CK(clk),
	.D(n_48),
	.Q(acc_out[4]),
	.QN(n_31),
	.RN(rst_n));
   DFFRXL \acc_out_reg[9]  (.CK(clk),
	.D(n_57),
	.Q(acc_out[9]),
	.QN(n_30),
	.RN(rst_n));
   DFFRXL \acc_out_reg[0]  (.CK(clk),
	.D(n_50),
	.Q(acc_out[0]),
	.QN(n_29),
	.RN(rst_n));
   DFFRXL \acc_out_reg[1]  (.CK(clk),
	.D(n_49),
	.Q(acc_out[1]),
	.QN(n_28),
	.RN(rst_n));
   DFFRXL \acc_out_reg[7]  (.CK(clk),
	.D(n_59),
	.Q(acc_out[7]),
	.QN(n_27),
	.RN(rst_n));
   DFFRX4 \acc_out_reg[8]  (.CK(clk),
	.D(n_58),
	.Q(acc_out[8]),
	.QN(n_26),
	.RN(rst_n));
   DFFRXL \state_reg[0]  (.CK(clk),
	.D(n_41),
	.Q(state[0]),
	.QN(n_25),
	.RN(rst_n));
   DFFRXL busy_reg (.CK(clk),
	.D(n_42),
	.Q(busy),
	.QN(n_2),
	.RN(rst_n));
   DFFRXL \acc_out_reg[2]  (.CK(clk),
	.D(n_63),
	.Q(acc_out[2]),
	.QN(n_14),
	.RN(rst_n));
   DFFRXL \acc_out_reg[11]  (.CK(clk),
	.D(n_55),
	.Q(acc_out[11]),
	.QN(n_13),
	.RN(rst_n));
   DFFRXL \acc_out_reg[3]  (.CK(clk),
	.D(n_61),
	.Q(acc_out[3]),
	.QN(n_12),
	.RN(rst_n));
   DFFRXL \acc_out_reg[12]  (.CK(clk),
	.D(n_54),
	.Q(acc_out[12]),
	.QN(n_11),
	.RN(rst_n));
   DFFRXL \acc_out_reg[6]  (.CK(clk),
	.D(n_60),
	.Q(acc_out[6]),
	.QN(n_10),
	.RN(rst_n));
   DFFRXL \acc_out_reg[10]  (.CK(clk),
	.D(n_56),
	.Q(acc_out[10]),
	.QN(n_9),
	.RN(rst_n));
   DFFRXL \acc_out_reg[13]  (.CK(clk),
	.D(n_53),
	.Q(acc_out[13]),
	.QN(n_8),
	.RN(rst_n));
   DFFRXL \acc_out_reg[15]  (.CK(clk),
	.D(n_51),
	.Q(acc_out[15]),
	.QN(n_7),
	.RN(rst_n));
   DFFRXL \acc_out_reg[14]  (.CK(clk),
	.D(n_52),
	.Q(acc_out[14]),
	.QN(n_6),
	.RN(rst_n));
   DFFRXL \acc_out_reg[5]  (.CK(clk),
	.D(n_62),
	.Q(acc_out[5]),
	.QN(n_5),
	.RN(rst_n));
   DFFRXL done_reg (.CK(clk),
	.D(n_47),
	.Q(done),
	.QN(n_4),
	.RN(rst_n));
endmodule

